version: '3'
services:
  db:
    image: postgres:10.7-alpine
    environment:
      POSTGRES_DB: psql_local
      POSTGRES_USER: docker_user
      POSTGRES_PASSWORD: secret
    ports:
      - "15432:5432"
    # Uncomment to persist changes to your local dev environment
    # volumes:
    #   -./.local_dev/psql_local_data:/var/lib/postgresql/data/pgdata
